### ISSUE TITLE
Missing information (satellite height)

### ISSUE THREAD

**Issue by yreynaud** [umr-lops/xarray-safe-rcm#26]
For the processing of the elevation variable I need the satelliteHeight(xpath: `product/imageGenerationParameters/sarProcessingInformation/satelliteHeight`).
Is it possible to add it to your reader please?

**Comment by keewis** [comment]
This is part of #17, right? If so, yes, of course I can add those. However, I'm not sure when I will be able to complete that.

**Comment by yreynaud** [comment]
Yes it is, sorry I didn't notice it
