### ISSUE TITLE
pip/conda installable library

### ISSUE THREAD

**Issue by yreynaud** [umr-lops/xarray-safe-rcm#28]
It should be good to push the library on pypi and conda-forge even if it isn't the final version of the reader. That would permit to include the library in xsar config files and so make passing all checks on PR (https://github.com/umr-lops/xsar/pull/151)

**Comment by keewis** [comment]
The library is on PyPI now, but I'm going to wait a bit before adding it to `conda-forge`.

**Comment by yreynaud** [comment]
Okay, I have updated the installing syntax in xsar config and documentation files (on my fork). It will be merge later

**Comment by agrouaze** [comment]
conda recipe adressed here : https://github.com/conda-forge/staged-recipes/pull/22995#issuecomment-1573482939

**Comment by keewis** [comment]
let's try to have the PR to `staged-recipes` close this issue (not sure if that's possible, if not I will close manually)

**Comment by keewis** [comment]
auto-closing didn't work, unfortunately
