### ISSUE TITLE
meta.start_date format

### ISSUE THREAD

**Issue by vincelhx** [umr-lops/xarray-safe-rcm#34]
some files like ```/home/datawork-cersat-public/provider/asc-csa/satellite/l1/rcm/rcm1/SCLNB/GRD/2022/357/RCM1_OK2411022_PK2411802_1_SCLNB_20221223_124819_VV_VH_GRD```have meta.start_date format matching ```%Y-%m-%d %H:%M:%S.%f```. its the good format 

other like ```/home/datawork-cersat-public/provider/asc-csa/satellite/l1/rcm/rcm3/SCLNC/GRD/2023/089/RCM3_OK2496357_PK2497646_1_SCLNC_20230330_222809_VV_VH_GRD``` match ```%Y-%m-%d %H:%M:%S```

maybe it should be uniform to match ```%Y-%m-%d %H:%M:%S.%f```

**Comment by keewis** [comment]
it took me quite a while to answer, but I think this is / was an issue in `xsar`: I don't remember using `meta.start_date` anywhere within this library.
